[general]
style = "pills"

[palette]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[styles.pills.colors]
icon_bg = "lavender"
icon_fg = "crust"
text_bg = "surface0"

[styles.powerline]
# rainbow_path = false
rainbow_index_icon = false

[styles.powerline.colors]
rainbow = ["peach", "yellow", "green", "teal", "blue", "lavender"]

[styles.pills.left_zone]
use_git = true

[styles.pills.left_zone.git_colors]
# directory = "blue"
git_branch_icon = "overlay2"
git_branch = "mauve"
git_stashed = "subtext0"
git_deleted = "mauve"
git_staged = "sapphire"
git_modified = "yellow"
git_renamed = "peach"
git_untracked = "blue"
git_ahead = "green"
git_behind = "red"
git_conflicted = "red"

[styles.pills.right_zone]
enabled = true

[mode_indicator.powerline]
foreground = "peach"

[mode_indicator.pills]
icon_bg = "peach"

[icons]
fallback = ""

[icons.mapping]
Python = ""
R = "󰟔"
ansible = ""
ant = ""
apache2 = ""
apt = ""
atom = ""
aws = ""
babel = ""
bat = "󰭟"
bazel = ""
beam = ""
"beam.smp" = ""
bitbucket = ""
brew = ""
btm = ""
btop = ""
caffeinate = ""
cargo = ""
cfdisk = ""
clang = ""
claude = ""
clion = ""
cmake = ""
code = ""
"code-insiders" = ""
composer = ""
console = "󰞷"
crontab = ""
csharp = ""
curl = ""
dart = ""
deno = ""
dnf = ""
docker = ""
doctl = ""
dotnet = ""
dpkg = ""
eclipse = ""
elixir = ""
emacs = ""
fdisk = ""
firebase = ""
flutter = ""
gcc = ""
gcloud = ""
gdb = ""
gh = ""
ghc = ""
ghostty = ""
git = ""
gitlab = ""
gitui = ""
glances = ""
go = ""
gpg = ""
gping = ""
gradle = ""
grunt = ""
gulp = ""
helm = "󱃾"
heroku = ""
hg = ""
htop = ""
httpd = ""
hx = "󰔤"
idea = ""
iterm2 = ""
java = ""
jekyll = ""
jenkins = ""
jest = ""
jj = ""
julia = ""
just = ""
k9s = "󱃾"
kitten = "󰄛"
kitty = "󰄛"
kmux = ""
kubectl = "󱃾"
kubie = "󱃾"
laravel = ""
lazydocker = ""
lazygit = ""
lazyjj = ""
lf = ""
lfcd = ""
lldb = ""
lvim = ""
mactop = ""
make = ""
maven = ""
minikube = "󱃾"
mocha = ""
mongo = ""
mysql = ""
nala = ""
nano = ""
netbeans = ""
ng = ""
nginx = ""
node = ""
npm = ""
nu = ""
nvim = ""
openssl = ""
pacman = ""
parted = ""
paru = ""
perl = ""
php = ""
ping = ""
pip = ""
pip3 = ""
powershell = ""
psql = ""
puppet = ""
pycharm = ""
python = ""
python3 = ""
ranger = ""
react = ""
redis = ""
rmpc = "󰝚"
rsync = ""
ruby = ""
rustc = ""
rustup = ""
scala = ""
scp = "󱁥"
screen = ""
sqlite = ""
ssh = ""
stack = ""
sublime_text = ""
sudo = ""
svn = ""
swift = ""
systemctl = ""
tcsh = ""
terraform = "ﲽ"
tickrs = ""
tig = ""
tmux = ""
top = ""
topgrade = "󰚰"
travis = ""
tsc = ""
unicorn = "󱗃"
unzip = ""
vagrant = ""
valgrind = ""
vi = ""
vim = ""
virtualbox = ""
visualstudio = ""
vue = "﵂"
webpack = ""
weechat = "󰭹"
wget = ""
wordpress = ""
y = "󰇥"
yarn = ""
yay = ""
yazi = "󰇥"
yum = ""
zig = "↯"
zip = ""
zsh = ""
