config:
  windows:
    envs:
      path:
        - 'C:\Users\cwel\.local\share\nvim-data\mason\bin'
        - 'C:\Program Files\Git\usr\bin'
        - 'C:\Users\cwel\.local\bin'
      others:
        HOME: 'C:\Users\cwel'
        XDG_CONFIG_HOME: 'C:\Users\cwel\.config'
        XDG_PROJECTS_DIR: 'C:\Users\cwel\Projects'
        XDG_CACHE_HOME: 'C:\Users\cwel\.cache'
        XDG_DATA_HOME: 'C:\Users\cwel\.local\share'
        XDG_STATE_HOME: 'C:\Users\cwel\.local\state'
        XDG_BIN_HOME: 'C:\Users\cwel\.local\bin'
        YAZI_CONFIG_HOME: 'C:\Users\cwel\.config\yazi'
        YAZI_FILE_ONE: 'C:\Program Files\Git\usr\bin\file.exe'
        KOMOREBI_CONFIG_HOME: 'C:\Users\cwel\.config\komorebi'
        EZA_CONFIG_DIR: 'C:\Users\cwel\.config\eza'
        GNUPGHOME: 'C:\Users\cwel\.local\share\gnupg'
        VBOX_USER_HOME: 'C:\Users\cwel\.local\share\virtualbox'
        VAGRANT_HOME: 'C:\Users\cwel\.local\share\vagrant'
        VAGRANT_DEFAULT_PROVIDER: 'virtualbox'
        BAT_CONFIG_DIR: 'C:\Users\cwel\.config\bat'
        DOCKER_CONFIG: 'C:\Users\cwel\.config\docker'
        PIPX_HOME: 'C:\Users\cwel\.local\share\pipx'
        PIPX_GLOBAL_HOME: 'C:\Users\cwel\.local\share\pipx'
        DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
        LESSHISTFILE: 'C:\Users\cwel\.cache\.lesshsts'
        CARGO_HOME: 'C:\Users\cwel\.local\share\cargo'
        RUSTUP_HOME: 'C:\Users\cwel\.local\share\rustup'
        GOPATH: 'C:\Users\cwel\.local\share\go'
        NPM_CONFIG_CACHE: 'C:\Users\cwel\.cache\npm'
        YARN_CACHE_FOLDER: 'C:\Users\cwel\.cache\npm'
        PNPM_HOME: 'C:\Users\cwel\.local\share\pnpm'
        XAUTHORITY: 'C:\Users\cwel\.local\state\.Xauthority'
        RCLONE_CONFIG_DIR: 'C:\Users\cwel\.config\rclone'
        PYTHON_HISTORY: 'C:\Users\cwel\.local\share\python\history'
        NODE_REPL_HISTORY: 'C:\Users\cwel\.local\share\node_repl_history'

    features:
      enable:
        - 'VirtualMachinePlatform'
        - 'Microsoft-Windows-Subsystem-Linux'
        - 'NetFx3'
        - 'NetFx4-AdvSrvs'
      disable:
        - 'MicrosoftWindowsPowerShellV2'

    startup:
      shortcuts:
        - name: 'kb'
          target: 'C:\Users\cwel\.local\bin\kb.ahk'

    symlinks:
      "%LocalAppData%\\Packages\\Microsoft.WindowsTerminal_8wekyb3d8bbwe\\LocalState\\settings.json": "%HOME%\\.local\\share\\chezmoi\\home\\dot_config\\windows-terminal\\settings.json"
      "%HOME%\\Documents\\Powershell\\Microsoft.PowerShell_profile.ps1": "%HOME%\\.config\\powershell\\profile.ps1"
      "%HOME%\\Documents\\Powershell\\Microsoft.VSCode_profile.ps1": "%HOME%\\.config\\powershell\\profile.ps1"
      "%HOME%\\Documents\\Powershell\\powershell.config.json": "%HOME%\\.config\\powershell\\powershell.config.json"
      "%APPDATA%\\topgrade.toml": "%HOME%\\.config\\topgrade.toml"
