[flavor]
dark = "catppuccin-mocha"

[icon]
prepend_dirs = [
  { name = "src", text = "", },
  { name = ".Trash", text = "", },
  { name = ".cache", text = "", },
  { name = ".ssh", text = "󰢬", },
  { name = ".local", text = "󰉌", }, 
]
